import type { IdentityAuditAction, IdentityDocumentType, IdentityStatus } from "./identity.types.js";

export const IDENTITY_STATUSES: IdentityStatus[] = ["PENDING", "IN_REVIEW", "VERIFIED", "REJECTED", "EXPIRED"];

export const IDENTITY_DOCUMENT_TYPES: IdentityDocumentType[] = ["DOCUMENT_FRONT", "DOCUMENT_BACK", "SELFIE"];

export const IDENTITY_AUDIT_ACTIONS: IdentityAuditAction[] = [
  "IDENTITY_STARTED",
  "IDENTITY_PERSONAL_DATA_UPDATED",
  "IDENTITY_DOCUMENT_FRONT_UPLOADED",
  "IDENTITY_DOCUMENT_BACK_UPLOADED",
  "IDENTITY_SELFIE_UPLOADED",
  "IDENTITY_DECLARATION_ACCEPTED",
  "IDENTITY_SUBMITTED",
  "IDENTITY_APPROVED",
  "IDENTITY_REJECTED",
  "IDENTITY_EXPIRED"
];

export const REQUIRED_IDENTITY_DOCUMENT_TYPES: IdentityDocumentType[] = ["DOCUMENT_FRONT", "DOCUMENT_BACK", "SELFIE"];

