services:
  postgres:
    image: postgres:16
    container_name: firma-digital-postgres
    environment:
      POSTGRES_DB: firma_digital
      POSTGRES_USER: firma
      POSTGRES_PASSWORD: firma
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
